# Generated by Django 4.0.4 on 2022-04-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyQC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyqc',
            name='DI',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='dailyqc',
            name='EI',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='dailyqc',
            name='EIt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
    ]
