# Generated by Django 4.0.3 on 2022-05-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyQC', '0002_dailyqc_di_dailyqc_ei_dailyqc_eit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyqc',
            name='D03',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqc',
            name='D4',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqc',
            name='DI',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqc',
            name='EI',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqc',
            name='EIt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqc',
            name='MTF10',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqc',
            name='MTF20',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqc',
            name='MTF50',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqc',
            name='SDNR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqc',
            name='SIGNAL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqc',
            name='SNR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='dailyqc',
            name='mAs',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, null=True),
        ),
    ]
