# Generated by Django 4.0.4 on 2022-05-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyQC', '0003_alter_dailyqc_d03_alter_dailyqc_d4_alter_dailyqc_di_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyqc',
            name='signal_image',
            field=models.BinaryField(null=True),
        ),
    ]
