# Generated by Django 4.0.4 on 2022-05-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyQC', '0005_dailyqc_contrast_dailyqc_dap_dailyqc_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyqc',
            name='deltaCONTRAST',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyqc',
            name='deltaD03',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyqc',
            name='deltaD4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyqc',
            name='deltaDAP',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyqc',
            name='deltaDI',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyqc',
            name='deltaEI',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyqc',
            name='deltaMAS',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyqc',
            name='deltaMTF50',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyqc',
            name='deltaSDNR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyqc',
            name='deltaSIGNAL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyqc',
            name='deltaSNR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyqc',
            name='diffKV',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
