# Generated by Django 4.0.4 on 2022-05-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyQC', '0007_dailyqc_deltamtf10_dailyqc_deltamtf20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyqc',
            name='CONTRAST',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, null=True),
        ),
    ]
