# Generated by Django 4.0.4 on 2022-05-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyQC', '0008_alter_dailyqc_contrast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyqc',
            name='CONTRAST',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True),
        ),
    ]
